### ISSUE TITLE
能加我进yiier么？

### ISSUE THREAD

**Issue by qiansen1386** [yiier/forum#1]
亦清哥，阿飞，大家都加下我的群（[Yii2兴趣小组](http://shang.qq.com/wpa/qunwpa?idkey=85c1c9eabc2334d83ccd994a4331b90c5d1a40be53c5b906fe8bc8f0a5334dfd)）吧？能加我进yiier么？

我也想加入开发。主要是想研究下markdown的部分，将来把翻译好的文档直接导入进来。另外yii2.cn的域名我也贡献出来。当初买的时候主要是他够短，.cn本身确实操蛋，不过科技类不是社会类，应该相对宽松些，毕竟很多论坛像liebao.cn, Maxthon.cn, thinkphp.cn,  symfony.cn在国内也都还活着，小心点，不放水区，应该不会有太大问题。

**Comment by forecho** [comment]
到时候做一个 敏感词过滤的功能

**Comment by djfly** [comment]
已加！
