### ISSUE TITLE
简陋的模块设计

### ISSUE THREAD

**Issue by forecho** [yiier/forum#4]
最近这两天在加班，昨晚还加班到3点，ಥ_ಥ，废话不多说，为了不浪费大家的时间，我设计了最初版本的模块图，非常的简陋，很多模块其实我也不知道该如何设计，需要讨论下。
大家有什么建议都可以来说说，反正是学习嘛。

![yii-forum](https://f.cloud.github.com/assets/1725326/2301464/7372e1c0-a146-11e3-9c09-3666091c6749.png)

我认为 coding 之前，详细设计很有必要。

**Comment by qiansen1386** [comment]
可不可以不光是论坛，设计一个时候Yii用户交流学习的平台，就是要包括CRM，和Yii2中文文档发布，在线手册查询和简单的论坛交流的站点。
主体模块包括：论坛和CRM，用户及权限，在线手册，插件发布，问答（？），后台管理。
详细是CRM本身是介于博客跟论坛之间的东东，支持Markdown或所见即所得编辑。
用户及权限，如forecho所言，很完善了。
在线手册，我想做一个读取后台markdown文件然后转换成网页显示出来，并支持中英文对照功能的在线手册，包括先一步翻译出来的在线指南，和Yii2-blog demo，以及可能后期陆续加入的源码注释和手册的查询。
问答模块，可以直接拿一个现成的python开发的类知乎问答模块植入进来。也可以自己开发，主要是有顶踩机制加上标签机制，把最精华的问题顶上来，用标签分流好问题，将来也可以把精华的问题纳入到CRM里去。踩功能，最好限制一下，除非问题天怒人怨，或者违法乱纪，否则一般不允许踩。也可以考虑整合进CRM及论坛系统。
插件发布模块，是我们应该号召国人自己开发yii插件。不要让老毛子天天霸占yii插件的列表。我们把一些中国开发的独特插件也发布到国际上去。但是某些国际上一般用不到的插件，比如腾讯，微博，人人，的登陆模块，或者百度的Ueditor，阿里的AliceUI的整合插件，可能国外人用不上，咱们却可能经常用的插件，自己发布进来，当然，也可以考虑整合进CRM及论坛系统。

各位觉得如何？

**Comment by djfly** [comment]
节点我已经搞好了，

**Comment by qiansen1386** [comment]
比如：
http://ruby-china.org
http://www.pythontab.com/

**Comment by qiansen1386** [comment]
@djfly 节点是啥？

**Comment by djfly** [comment]
主要方向是

1.发贴网友可以交流，

2.把汉化工作做好，中英文对照的在线手册很有必要，学官方用markdown书写

3.wiki整理有用的资料

做好这三点就足够了

**Comment by qiansen1386** [comment]
手册，论坛，CRM

**Comment by djfly** [comment]
节点就是分类，我用了无限分类了

**Comment by forecho** [comment]
@qiansen1386 问答模块 和 插件发布模块 都可以作为一个节点就可以了
在线手册 这个不错，可以加上。
赞同 @djfly 说的，最初版本不要搞的太复杂。

**Comment by forecho** [comment]
@qiansen1386 那你这个在线手册功能就不需要用数据库了吗？直接读取文件？

**Comment by forecho** [comment]
@qiansen1386 我大部分设计都是参考 Ruby-China 的

**Comment by forecho** [comment]
修改之后的设计 你们看怎么样？
![yii-forum](https://f.cloud.github.com/assets/1725326/2303280/c9f874a4-a1b1-11e3-86be-e6a0a8532c4e.png)

**Comment by qiansen1386** [comment]
@forecho 我是有这方面的打算，将来如果官方文档修改了，我们直接覆盖掉旧文件就好。不过，从开发难度的角度考虑应该是全都存数据库比较容易实现和掌控。可能后期再考虑让他直接读文件，这样可以减少大量的数据库IO。

**Comment by forecho** [comment]
@qiansen1386 那 在线文档 模块就交给你了

**Comment by qiansen1386** [comment]
@forecho 我现在没太有底，等我研究一下yii2的markdown库先。
Update: 你们都看过[这孩子](http://demos.krajee.com/)的项目么？yii2-Bootstrap+他的这几个扩展之后简直太屌了。Markdown这一块就解决了。这样就没有markdown方面的技术难题了。

关于数据结构方面，我应该把这个东西整合进wiki系统里面呢？还是独立的数据表？

**Comment by djfly** [comment]
他搞的太多了，markdown有现成的，yii本身就带了一个转换的，只是没有前端编辑器

https://github.com/kartik-v/yii2-markdown 有人写了这个，看看是不是用这个

**Comment by qiansen1386** [comment]
@djfly 我说的就是那个，忘了放地址了，哈哈不好意思。

刚刚查了下图片和文档的CDN可以考虑用[七牛](http://www.qiniu.com/pricing)，前10G流量和空间免费。起步阶段就没有成本了。他的SDK支持PHP的。[注册地址，绑定手机之后就能免费用了，感觉还不错](https://portal.qiniu.com/signup?code=3lbidj10cl0lu)

**Comment by djfly** [comment]
七牛不错
@forecho 你愿意干那部分？

**Comment by forecho** [comment]
@qiansen1386 七牛还不错，就用这个。在线文档你还是用独立的数据表吧，方便以后。
@djfly 我来做帖子的模块吧
