### ISSUE TITLE
关于数据结构的设计

### ISSUE THREAD

**Issue by ITGodzilla** [yiier/forum#9]
诸位: 为了形成可读的数据字典 我觉得建表 或者增加字段的时候给 表和 字段加 注释是很有必要的 
提议一个小小的规范 字段注释 就以在页面上显示的 label 为标准命名 
例如 

```
username  注释为 "用户名"  而非 “用户账号字段”
```

**Comment by djfly** [comment]
支持 :+1:

**Comment by forecho** [comment]
嗯 同意 ![image](https://f.cloud.github.com/assets/1725326/2407423/08eac9e0-aa8c-11e3-8712-61aaefd15da2.png)

**Comment by qiansen1386** [comment]
酱……额，支持。 :+1:
